INSERT INTO geo.vue_activite_geo (id_ligne,libelle) VALUES
	 ('020','TANA INVOICES'),
	 ('070','TANA EDITORIAL SERVICES'),
	 ('030','TANA PATENT MANAGEMENT'),
	 ('065','TANA SOCIAL, HEALTH & ADMI'),
	 ('045','TANA SECTEUR BANQUES'),
	 ('035','TANA CONTENT DIGITALIZATION');